### ISSUE TITLE
I restarted the server after putting the jar to the mods then this happens.

### ISSUE THREAD

**Issue by yasirukavishka** [blackassasin1234/MindustryJDA#1]
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
Eclipse OpenJ9 VM (build openj9-0.18.1, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200122_511 (JIT enabled, AOT enabled)
OpenJ9 - 51a5857d2
OMR - 7a1b0239a
JCL - 8cf8a30581 based on jdk8u242-b08)
:/home/container$ java -Xms128M -Xmx256M -jar server-release.jar config port 9002
[05-01-2020 | 23:47:00] [E] Failed to load mod file config/mods/MindustryJDA-1.2-SNAPSHOT.jar. Skipping.
[05-01-2020 | 23:47:00] [E] java.lang.NoClassDefFoundError: io.anuke.mindustry.plugin.Plugin
at java.lang.ClassLoader.defineClassImpl(Native Method)
at java.lang.ClassLoader.defineClassInternal(Unknown Source)
at java.lang.ClassLoader.defineClass(Unknown Source)
at java.security.SecureClassLoader.defineClass(Unknown Source)
at java.net.URLClassLoader.defineClass(Unknown Source)
at java.net.URLClassLoader.access$400(Unknown Source)
at java.net.URLClassLoader$ClassFinder.run(Unknown Source)
at java.security.AccessController.doPrivileged(Unknown Source)
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClassHelper(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at mindustry.mod.Mods.loadMod(Mods.java:648)
at mindustry.mod.Mods.load(Mods.java:247)
at mindustry.Vars.init(Vars.java:275)
at mindustry.server.ServerLauncher.init(ServerLauncher.java:58)
at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:75)
at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:63)
Caused by: java.lang.ClassNotFoundException: io.anuke.mindustry.plugin.Plugin
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClassHelper(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
... 18 more
[05-01-2020 | 23:47:07] [I] 5 mods loaded.
[05-01-2020 | 23:47:07] [I] <io>: Server loaded. Type 'help' for help.
[05-01-2020 | 23:47:07] [I] <io>: If you wish to assign a custom domain to your server, please contact aze#0001 on discord for instructions.
[05-01-2020 | 23:47:07] [I] <io>: You need to start hosting to run the server. Type 'host' to start hosting.
[05-01-2020 | 23:47:07] [I] Found 1 command-line arguments to parse.
[05-01-2020 | 23:47:07] [I] Found 1 startup commands.
[05-01-2020 | 23:47:07] [I] port set to 9002.
[05-01-2020 | 23:47:07] [I] <io>: Loading map...
[05-01-2020 | 23:47:10] [I] <io>: Map loaded.
[05-01-2020 | 23:47:10] [I] Opened a server on port 9002.
[05-01-2020 | 23:47:10] [I] <io>: You can connect to the server connect using the custom domain. 'community.mindustry.io:9002'

**Comment by DeltaNedas** [comment]
you use openj9, use hotspot jvm

**Comment by blackassasin1234** [comment]
This is due to the update in Jan/Feb when Anuke changes the package name and this plugin has not been updated before that, i recommend using another plugin (You probably already did by now) as i don't know when i'll be able to update/recode it.
